#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

DESTDIR = Debug
CONFIG += debug

DEFINES += 
LIBS += -L/usr/lib/arm-linux-gnueabihf -ludev
INCLUDEPATH += /usr/include Debug
QMAKE_LFLAGS += 
QMAKE_CXXFLAGS += -ggdb -fpermissive -std=c++14 
QMAKE_CFLAGS += -ggdb -fpermissive -std=c++14 
COMMONFLAGS += 
